name = "Bruhat"
uuid = "2c031b90-0c76-4089-b0fc-d8363c532777"
authors = ["Bailey Whitbread <baileycwhitbread@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
