function verify_lusztig_on_chain(A::Matrix{Bool})
    # Checks tables generated by intersections_geometric_ordered(G)
    # A is a matrix of true/false = 1/0 according to whether the poly was non-zero
    # We need to check every row is of the form 0 ... 0 1 ... 1 (potentially zero 0's or zero 1's)
    for row in eachrow(A)
        seen_one = false
        for val in row
            if !seen_one
                if val
                    seen_one = true
                end
            else
                if !val
                    return false  # Found a 0 after a 1
                end
            end
        end
    end
    return true  # All rows satisfy the required pattern
end